name: startup_hr
description: Startup HR - ระบบจัดการพนักงาน (Flutter UI ตาม lab3.md)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Noto Sans Thai
      fonts:
        - asset: assets/fonts/NotoSansThai-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansThai-Bold.ttf
          weight: 700